import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";

const Encode_Sans = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_Sans.className}  antialiased`}>
        <div className="flex flex-col justify-between min-h-screen">
          <NavBar />
          <div className="container">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
