import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import Footer from "./_components/Footer";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import NextAuthProviders from "@/providers/components/nextauth.providers";
import Providers from "@/providers/components/reactQuery.provider";
import { ToastContainer } from "react-toastify";
import SubCategoriesProvider from "./context/SubCategoriesContext";
import BrandsProvider from "./context/BrandsContext";

const Encode_Sans = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Encode_Sans.className}  antialiased`}>
        <Providers>
          <ToastContainer />
          <SubCategoriesProvider>
            <BrandsProvider>
              <div className="min-h-screen">
                <NextAuthProviders>
                  <NavBar />
                  <div className="container">{children}</div>
                </NextAuthProviders>
              </div>
            </BrandsProvider>
          </SubCategoriesProvider>
        </Providers>
      </body>
    </html>
  );
}
